# Generated by Django 4.2.18 on 2025-02-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('matricula', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome', max_length=20)),
                ('dataInicial', models.DateField(help_text='Data Inicial')),
                ('dataFinal', models.DateField(help_text='Data Final')),
            ],
        ),
    ]
