# Generated by Django 4.2.18 on 2025-02-11 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrutores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrutores',
            old_name='data_registro',
            new_name='titulo',
        ),
    ]
