# Generated by Django 4.2.18 on 2025-02-14 23:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipodeatividade', '0003_alter_tipodeatividade_codigo'),
        ('instrutores', '0002_rename_data_registro_instrutores_titulo'),
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('horarioAula', models.TimeField(blank=True, help_text='Horário Aula')),
                ('duracaoAula', models.TimeField(blank=True, help_text='Duração Aula')),
                ('dataInicial', models.DateField(blank=True, help_text='Data Inicial')),
                ('dataFinal', models.DateField(blank=True, help_text='Data Final', null=True)),
                ('codigoTipoDeAtividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipodeatividade.tipodeatividade')),
                ('idInstrutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrutores.instrutores')),
                ('matriculaMonitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.alunos')),
            ],
        ),
        migrations.CreateModel(
            name='TurmaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_matricula', models.DateField(default=django.utils.timezone.now, help_text='Data da matrícula do aluno.')),
                ('data_fim_matricula', models.DateField(blank=True, help_text='Data fim de matrícula do aluno.', null=True)),
                ('matricula_aluno', models.ForeignKey(help_text='Matrícula do aluno.', on_delete=django.db.models.deletion.CASCADE, to='alunos.alunos')),
                ('numero_turma', models.ForeignKey(help_text='Turma do aluno.', on_delete=django.db.models.deletion.CASCADE, to='turmas.turmas')),
            ],
        ),
    ]
