# Generated by Django 4.2.18 on 2025-02-14 23:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrutores', '0002_rename_data_registro_instrutores_titulo'),
        ('tipodeatividade', '0003_alter_tipodeatividade_codigo'),
        ('alunos', '0001_initial'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('numero', models.AutoField(help_text='Informe a turma do Aluno', primary_key=True, serialize=False)),
                ('horario_aula', models.TimeField(help_text='Informe a hora em que a hora da aula da Turma')),
                ('duracao_aula', models.SmallIntegerField(default=30, help_text='Informe a duração da aula da Turma')),
                ('data_inicial', models.DateField(default=datetime.datetime(2025, 2, 14, 23, 25, 52, 535606, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial da Turma')),
                ('data_final', models.DateField(default=datetime.datetime(2025, 2, 14, 23, 25, 52, 535606, tzinfo=datetime.timezone.utc), help_text='Informe a data final da Turma')),
                ('codigo_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipodeatividade.tipodeatividade')),
                ('id_instrutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instrutores.instrutores')),
                ('matricula_monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.alunos')),
            ],
        ),
        migrations.AlterField(
            model_name='turmaaluno',
            name='numero_turma',
            field=models.ForeignKey(help_text='Turma do aluno.', on_delete=django.db.models.deletion.CASCADE, to='turmas.turma'),
        ),
        migrations.DeleteModel(
            name='Turmas',
        ),
    ]
