# Generated by Django 4.2.18 on 2025-02-15 00:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
        ('turmas', '0002_turma_alter_turmaaluno_numero_turma_delete_turmas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ['numero']},
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_final',
            field=models.DateField(default=datetime.datetime(2025, 2, 15, 0, 25, 9, 954627, tzinfo=datetime.timezone.utc), help_text='Informe a data final da Turma'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_inicial',
            field=models.DateField(default=datetime.datetime(2025, 2, 15, 0, 25, 9, 954627, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial da Turma'),
        ),
        migrations.AlterField(
            model_name='turmaaluno',
            name='data_inicio_matricula',
            field=models.DateField(default=datetime.datetime(2025, 2, 15, 0, 25, 9, 954627, tzinfo=datetime.timezone.utc), help_text='Data da matrícula do aluno.'),
        ),
        migrations.CreateModel(
            name='Ausencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ausencia', models.DateField(default=datetime.datetime(2025, 2, 15, 0, 25, 9, 954627, tzinfo=datetime.timezone.utc), help_text='Data da falta do aluno.')),
                ('matricula_aluno', models.ForeignKey(help_text='Matrícula do aluno.', on_delete=django.db.models.deletion.CASCADE, to='alunos.alunos')),
                ('numero_turma', models.ForeignKey(help_text='Turma do aluno.', on_delete=django.db.models.deletion.CASCADE, to='turmas.turma')),
            ],
        ),
    ]
